name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Binary
        run: cargo build --release
      - name: Package
        run: |
          tar -czvf gitlink-macos.tar.gz -C target/release gitlink
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: gitlink-macos.tar.gz
