name: Release macOS
on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
        env:
          GITLINK_CLIENT_ID: ${{ secrets.GITLINK_CLIENT_ID }}
      - name: Archive
        run: tar -czvf gitlink-macos.tar.gz -C target/release gitlink
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: gitlink-macos.tar.gz

